const lessons=[
 {day:1,title:"Apresentar-se",goal:"Identificar nomes, cumprimentos e apresentações.",videoId:"WR9_nsLyaEY",structure:"I am → I'm · You are → You're · Are you...?",qs:[["Quem está chegando ao novo apartamento?",["Pete","Anna","Marsha"],1],["Qual frase é usada ao conhecer alguém?",["See you tomorrow","Nice to meet you","Good night"],1],["Complete: ___ you Anna?",["Is","Are","Am"],1]]},
 {day:2,title:"Pessoas e lugares",goal:"Entender quem é uma pessoa e de onde ela vem.",videoId:"1-U7o9xjWQc",structure:"I am · you are · he/she is · Where are you from?",qs:[["Anna é nova em qual cidade?",["D.C.","Boston","São Paulo"],0],["Quem é a colega de apartamento de Anna?",["Pete","Marsha","Jonathan"],1],["Complete: She ___ nice.",["am","are","is"],2]]},
 {day:3,title:"Entender pelo contexto",goal:"Usar pistas para compreender a situação.",videoId:"IEA9LMy-N3M",structure:"I want to... · Is there...? · This is...",qs:[["Por que Anna telefona?",["Procura um supermercado","Procura um hotel","Quer trabalhar"],0],["O que acontece na primeira ligação?",["Ninguém atende","É o número errado","Marsha não entende"],1],["O supermercado fica...",["longe","fechado","na mesma rua"],2]]},
 {day:4,title:"Identificar objetos",goal:"Distinguir is, have e objetos comuns.",videoId:"Z5PF-vJdUdc",structure:"It is... · It isn't... · I have...",qs:[["O que Anna procura?",["Uma caneta","Um telefone","Uma chave"],0],["Qual objeto mostra o mundo?",["pillow","map","toy"],1],["I ___ a pen in my bag.",["am","is","have"],2]]},
 {day:5,title:"Cômodos e ações",goal:"Inferir um lugar pela ação realizada.",videoId:"lDaZB5BBw7M",structure:"I am in... · I cook/sleep/wash in...",qs:[["Onde as pessoas cozinham?",["bedroom","kitchen","bathroom"],1],["Qual ação indica o quarto?",["sleep","cook","wash"],0],["I wash in this room. Qual lugar?",["living room","bathroom","bedroom"],1]]},
 {day:6,title:"Pedir direções",goal:"Entender a localização usando palavras-chave.",videoId:"T3AJ29_2IX8",structure:"Where is...? · next to · Go straight · Turn...",qs:[["Qual pergunta pede localização?",["Who is the gym?","Where is the gym?","What time is the gym?"],1],["Next to significa...",["ao lado de","longe de","em frente"],0],["Complete: ___ left.",["Turn","Sleep","Have"],0]]},
 {day:7,title:"Revisão semanal",goal:"Verificar retenção e reconhecer ações em andamento.",videoId:"Ka33lX-kbMg",structure:"I am studying · What are you doing?",qs:[["I ___ from Brazil.",["is","am","are"],1],["Qual pergunta pede localização?",["Where is it?","Who is it?","How old is it?"],0],["I am ___ English now.",["study","studying","studies"],1]]}
];
const initial={currentDay:1,completed:[],answers:{},scores:{},minutes:0,weekEvaluated:false,recommendation:""};
let state={...initial,...JSON.parse(localStorage.getItem("inglesNoRitmo")||"{}")};
const save=()=>localStorage.setItem("inglesNoRitmo",JSON.stringify(state));
function toast(t){const el=document.querySelector("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function renderLesson(){const l=lessons[state.currentDay-1],done=state.completed.includes(l.day);document.querySelector("#lessonCard").innerHTML=`<div class="lesson-head"><div><span class="lesson-number">DIA ${l.day} DE 7</span><h2>${l.title}</h2><p>${l.goal}</p></div><span class="time-badge">◷ 30 minutos</span></div><div class="lesson-body"><div class="media-panel"><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/${l.videoId}?rel=0" title="Vídeo da aula ${l.day}: ${l.title}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><p class="listen-tip"><strong>1ª vez:</strong> sem legenda · <strong>2ª vez:</strong> legenda em inglês</p><div class="structure"><strong>Estrutura do dia</strong><br>${l.structure}</div></div><form class="exercise-panel" id="quizForm"><h3>Verifique sua compreensão</h3>${l.qs.map((q,i)=>`<div class="question"><p>${i+1}. ${q[0]}</p>${q[1].map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" ${state.answers[l.day]?.[i]==j?"checked":""}> ${o}</label>`).join("")}</div>`).join("")}<div class="feedback ${done?"show":""}">${done?`Aula concluída · ${state.scores[l.day]}/${l.qs.length} respostas corretas.`:""}</div><div class="actions"><button type="submit" class="primary">${done?"Atualizar respostas":"Concluir aula"}</button><button type="button" class="primary whatsapp" id="whatsapp">Enviar pelo WhatsApp</button></div></form></div>`;
 document.querySelector("#quizForm").onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),ans=l.qs.map((_,i)=>Number(data.get(`q${i}`)));if(ans.some(Number.isNaN)){toast("Responda às três questões.");return}state.answers[l.day]=ans;state.scores[l.day]=ans.filter((a,i)=>a===l.qs[i][2]).length;if(!state.completed.includes(l.day)){state.completed.push(l.day);state.minutes+=30}if(l.day<7)state.currentDay=l.day+1;save();renderAll();toast("Aula concluída. Muito bem!")};
 document.querySelector("#whatsapp").onclick=()=>{const msg=`Inglês — Semana 1, Dia ${l.day}\n${l.title}\nObjetivo: ${l.goal}\nDuração: 30 minutos.\nAbrir portal: ${location.href.split("#")[0]}`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
}
function renderWeek(){document.querySelector("#weekGrid").innerHTML=lessons.map(l=>`<article class="day-card ${state.completed.includes(l.day)?"done":""}" data-day="${l.day}"><strong>${state.completed.includes(l.day)?"✓ ":""}Dia ${l.day}</strong><span>${l.title}</span></article>`).join("");document.querySelectorAll(".day-card").forEach(c=>c.onclick=()=>{state.currentDay=Number(c.dataset.day);save();switchView("hoje")});const unlocked=state.completed.length===7;document.querySelector("#assessmentCard").className=`assessment-card ${unlocked?"":"locked"}`;document.querySelector("#assessmentCard").innerHTML=`<p class="eyebrow">AVALIAÇÃO SEMANAL</p><h2>${unlocked?"Pronto para avaliar a semana":"Conclua as sete aulas"}</h2><p>${unlocked?"O sistema analisará acertos, audição e sustentabilidade para preparar a próxima semana.":`${7-state.completed.length} aula(s) restante(s).`}</p>${unlocked?`<div class="actions"><button class="primary" id="evaluate">Gerar próxima semana</button></div>`:""}`;if(unlocked)document.querySelector("#evaluate").onclick=evaluateWeek}
function evaluateWeek(){const total=lessons.reduce((n,l)=>n+l.qs.length,0),correct=Object.values(state.scores).reduce((a,b)=>a+b,0),pct=Math.round(correct/total*100);state.weekEvaluated=true;state.recommendation=pct>=80?`Resultado: ${pct}%. Semana 2 liberada no modo A2 inicial, com mais compreensão contextual e 20% de revisão.`:pct>=60?`Resultado: ${pct}%. Semana 2 seguirá adiante com reforço de 20% nos pontos frágeis.`:`Resultado: ${pct}%. A próxima semana consolidará o A1 com novos exemplos e mais escuta segmentada.`;save();renderAll();toast("Recomendação da Semana 2 gerada!")}
function renderStats(){const totalAnswered=Object.values(state.answers).reduce((n,a)=>n+a.length,0),correct=Object.values(state.scores).reduce((a,b)=>a+b,0);document.querySelector("#completedStat").textContent=state.completed.length;document.querySelector("#minutesStat").textContent=`${state.minutes} min`;document.querySelector("#accuracyStat").textContent=totalAnswered?`${Math.round(correct/totalAnswered*100)}%`:"—";document.querySelector("#adaptiveMessage").textContent=state.recommendation||"Conclua a primeira semana para receber uma recomendação adaptativa."}
function renderAll(){const n=state.completed.length;document.querySelector("#streakValue").textContent=n;document.querySelector("#progressFill").style.width=`${n/7*100}%`;document.querySelector("#progressText").textContent=`${n} de 7 aulas concluídas`;renderLesson();renderWeek();renderStats()}
function switchView(id){document.querySelectorAll(".view,.nav-link").forEach(x=>x.classList.remove("active"));document.querySelector(`#${id}`).classList.add("active");document.querySelector(`[data-view="${id}"]`).classList.add("active");scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav-link").forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="progresso-ingles-marcelo.json";a.click();URL.revokeObjectURL(a.href);toast("Backup exportado.")}
document.querySelector("#exportButton").onclick=exportData;document.querySelector("#backupButton").onclick=exportData;
document.querySelector("#importInput").onchange=async e=>{try{state={...initial,...JSON.parse(await e.target.files[0].text())};save();renderAll();toast("Progresso restaurado.")}catch{toast("Não foi possível ler esse backup.")}};
document.querySelector("#resetButton").onclick=()=>{if(confirm("Apagar todo o progresso salvo neste navegador?")){state={...initial,completed:[],answers:{},scores:{}};save();renderAll();toast("Progresso reiniciado.")}};
renderAll();
